import directorImage from "../../assets/images/director-principal/Director-image.jpg";
import type { DirectorData } from "./types";

export const directorData: DirectorData = {
  name: "Dr G.T Raju",
  topParagraphs: [
    "Bengaluru being the “Silicon Valley of India” or “IT Capital / Education Hub of India” due to its role as the nation’s leading Information Technology (IT) exporter, needs competent IT Professionals. A large number of information technology companies located in the city contributed 38% of India’s ₹1,442 billion IT exports and hosts nearly 40% of India’s start-ups. Infosys, Wipro, Mindtree, Mphasis, Flipkart, Myntra and other Indian technological organizations are headquartered in Bangalore. Top companies amongst the Fortune 500 have set up their Global Capability Center (GCC) in Bangalore. Government of Karnataka has an IT policy (2020-2025) aimed further cementing the position of Bangalore and thereby Karnataka as the IT hub of India.",
  ],
  remainingParagraphs: [
    "According to the National Employability report for Engineers by Aspiring Minds, nearly 80 percent of engineering graduates lack the requisite skills to be considered employable and only 3 percent possess skills that are needed for jobs in emerging technologies such as Artificial Intelligence (AI), Machine Learning (ML), Data Science (DS), Cyber Security, IoT, etc. The Government’s Digital India initiative is adopting Information Technology (IT) in general and AI & ML in particular as its new level, creating many more job opportunities that demand competent engineers in AI, ML and DS fields. Also, for economic growth and prosperity of our country, the need is to produce competent and professional IT Engineers. According to a recent survey, 58 million jobs in AI, ML and DS related fields will be created in the next few years.",

    "Approximately 1.2 lakh engineering graduates are passing out from all the Engineering colleges in Karnataka and projected manpower requirement in the state by 2025 is around 4 million plus only in IT sectors. Essentially to fill the demand-supply gap of IT engineers, there is a dearth for the reputed institutions which offer quality technical education and skill enhancement training in IT related areas. With the divine blessings of his holiness Jagadguru Padmabhushan Sri Sri Sri Dr. Balagangadharanatha Maha Swamiji, we at BGSKH Education trust started a new Engineering college BGSCET with 5 market-demanding /new-age Engineering and Technology programme: CSE | ISE | AIML | AIDS | CSD.",
    "BGSCET is the brainchild of his holiness Jagadguru Sri Sri Sri Dr. Nirmalanandanatha Maha Swamiji, President, Sri Adichunchanagiri Shikshana Trust and is driven by passionate Global Leaders, Industry & Academia Experts and Renowned Administrators. The institute has a quest for being an outstanding centre for learning and development of human resource, conducive to the fast changing national and international situations adhering to consistent policy of recruiting highly qualified teachers. BGSCET aims to impart quality technical education, undertake research and extension activities with emphasis on application and innovation that cater to the emerging societal needs through all-round development of students of all sections enabling them to be globally competitive and socially responsible citizens with core values. BGSCET with its functional infrastructure, state-of-the-art laboratories, affiliations and recognitions, networked partner industries and aspiring academically sound students, is keen to realize the vision of the Institute. It is the aspirations of faculty and management to nurture and boast of many innovators and entrepreneurs, besides producing quality engineers and technocrats for the society.",
    "We endeavour to equip our students into world class IT professionals along with ethical and spiritual values, so that they contribute effectively to the industry and society. Efforts of BGSCET are guided by our beloved revered Paramapoojya jagadguru Sri Sri Sri Dr. Nirmalanandanatha Maha Swamiji and an Advisory Board consisting of eminent professional personalities from Academia, Industry, Universities, Corporates and other bodies.",
    "We are sure, our students will have excellent professional career by availing the unique opportunities provided by BGSCET through classroom teaching, laboratory instructions, industrial trainings and participation in sports, cultural and other extra-curricular activities of interest. We wish you a very happy and satisfying student life at BGSCET and guarantee you a loving and caring atmosphere to make you socially responsible human beings reaching the pinnacle of your prospective career.",
  ],
  image: directorImage,
  imageAlt: "Dr G.T Raju, Director of BGSCET",
};
